// Generated by CoffeeScript 1.7.1
(function() {
  $('#sortable').sortable();

  $('#dosort').click(function() {
    var sorted;
    sorted = [];
    $('#sortable li').each(function() {
      return sorted.push($(this).attr('data-id'));
    });
    return $.post(location.href, {
      sorted: sorted
    }, function(ret) {
      if (!ret.code) {
        return alert('success');
      }
    }, 'json');
  });

}).call(this);
