// Generated by CoffeeScript 1.7.1
(function() {
  $('#payBtn').click(function() {
    var jsApiCall;
    jsApiCall = function() {
      return WeixinJSBridge.invoke('getBrandWCPayRequest', __initData.payParam, function(res) {
        if (res.err_msg === "get_brand_wcpay_request:ok") {
          return location.href = __initData.redirect;
        } else if (res.err_msg === "get_brand_wcpay_request:cancel") {
          return alert('你已经取消付款');
        }
      });
    };
    if (typeof WeixinJSBridge === "undefined") {
      if (document.addEventListener) {
        return document.addEventListener('WeixinJSBridgeReady', jsApiCall, false);
      } else if (document.attachEvent) {
        document.attachEvent('WeixinJSBridgeReady', jsApiCall);
        return document.attachEvent('onWeixinJSBridgeReady', jsApiCall);
      }
    } else {
      return jsApiCall();
    }
  });

}).call(this);
