// Generated by CoffeeScript 1.7.1
(function() {
  var config, jsApiList;

  jsApiList = ['chooseImage', 'uploadImage'];

  config = __initData.sign;

  config.jsApiList = jsApiList;

  wx.config(config);

  wx.ready(function() {
    return wx.checkJsApi({
      jsApiList: jsApiList,
      success: function(res) {
        var canUse, k, v, _ref;
        canUse = true;
        _ref = res.checkResult;
        for (k in _ref) {
          v = _ref[k];
          if (!v) {
            canUse = false;
            break;
          }
        }
        if (canUse) {
          return $('#upload').click(function() {
            return wx.chooseImage({
              success: function(imgRes) {
                var html, id, _i, _len, _ref1, _results;
                alert(JSON.stringify(imgRes.localIds));
                if (imgRes.localIds) {
                  if (imgRes.localIds.length > 1) {
                    return alert('只能选一张图片');
                  } else {
                    _ref1 = imgRes.localIds;
                    _results = [];
                    for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
                      id = _ref1[_i];
                      html = "<img src=\"" + id + "\" width=\"100%\" />";
                      $('#imgshow').html(html);
                      _results.push(wx.uploadImage({
                        localId: id,
                        isShowProgressTips: 1,
                        success: function(uploadRes) {
                          var serverId, uploadData;
                          serverId = uploadRes.serverId;
                          uploadData = {
                            tdi_id: serverId
                          };
                          if (document.getElementById('washinner').checked) {
                            uploadData.tdl_innerwash = 1;
                          }
                          return $.getJSON(location.href, uploadData, function(ret) {
                            alert(ret.msg);
                            if (!ret.code) {
                              return $('#upload').addClass('hide');
                            }
                          });
                        }
                      }));
                    }
                    return _results;
                  }
                }
              }
            });
          });
        } else {
          return alert('你的微信版本不支持上传图片');
        }
      }
    });
  });

}).call(this);
