// Generated by CoffeeScript 1.7.1
(function() {
  $('#addLine').click(function() {
    var newDom;
    newDom = $('.form-horizontal .form-group:first').clone();
    $('input,textarea', newDom).val('');
    return $('.form-horizontal .form-group:last').before(newDom);
  });

}).call(this);
