// Generated by CoffeeScript 1.7.1
(function() {
  var config, jsApiList;

  jsApiList = ['chooseWXPay'];

  config = {
    jsApiList: jsApiList
  };

  $.extend(config, __initData.sign);

  wx.config(config);

  wx.ready(function() {
    return wx.checkJsApi({
      jsApiList: jsApiList,
      success: function(res) {
        var payBtn, v, _i, _len;
        for (_i = 0, _len = jsApiList.length; _i < _len; _i++) {
          v = jsApiList[_i];
          if (!res.checkResult[v]) {
            alert('你的微信版本不支持微信支付');
            return false;
          }
        }
        payBtn = $('#paynew');
        return payBtn.click(function() {
          var payObj;
          payObj = __initData.jsPayParam;
          payObj.success = function(ret) {
            return alert('支付成功');
          };
          return wx.chooseWXPay(payObj);
        });
      }
    });
  });

}).call(this);
